[project]
name = "exam-drift-monitoring"
version = "1.0.0"
description = "Examen Drift Monitoring CANAL"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests==2.32.4",
    "evidently==0.6.7",
    "pandas==2.3.0",
    "numpy==2.0.2",
    "scikit-learn==1.7.0",
]
